name: "Workflow example"
on:
  schedule:
    - cron: '* * * * *'

jobs:
  hello:
    name: "Get weather"
    runs-on: ubuntu-latest
    steps:
      - name: Install curl
        run: sudo apt install curl
      - name: Call curl
        run: curl -o output.txt --location 'https://api.openweathermap.org/data/2.5/weather?lat=47.6740&lon=122.1215&units=imperial&appid=${{ secrets.WEATHER }}'
      - name: Display contents of file
        run: cat output.txt
