name: "Workflow example"
on:
  schedule:
    - cron: '* * * * *'

jobs:
  hello:
    name: "Get weather"
    runs-on: ubuntu-latest
    steps:
      - name: Display message
        run: sudo apt install curl
        curl -o output.txt https://api.openweathermap.org/data/3.0/onecall?lat=33.44&lon=-94.04&appid=${{ secrets.WEATHER }}
