name: "Workflow example"
on:
  schedule:
    - cron: '* * * * *'

jobs:
  hello:
    name: "Get weather"
    runs-on: ubuntu-latest
    steps:
      - name: Install curl
        run: sudo apt install curl
      - name: Call curl
        run: curl -o output.txt https://api.openweathermap.org/data/2.5/weather?lat=44.34&lon=10.99&appid=a8f4f8f47ac6126830d4246039ed3c64
      - name: Display contents of file
        run: cat output.txt
